# Enable mouse
CONFIG_ZMK_POINTING=y

# Set sleep timeout to 5min (5*60*1000ms)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000

# Bluetooth tweaks
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y

# Peripheral Battery Monitoring
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Zephyr ble settings
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=24
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

# Data Length Extension — bigger BLE packets (~4x throughput), big battery saver
CONFIG_BT_CTLR_DATA_LENGTH_MAX=69
